version: '3'

services:
  knowledge_graph:
    build:
      context: "./knowledge_graph"
      dockerfile: "Dockerfile"
    restart: always
    networks:
      - wcb

  knowledge_path:
    build:
      context: "./knowledge_path"
      dockerfile: "Dockerfile"
    restart: always
    networks:
      - wcb
      
  proxy:
    build:
      context: "./proxy"
      dockerfile: "Dockerfile"
    restart: always
    ports:
      - 8080:80
    networks:
      - wcb      

networks:
  wcb:
